"""create meals table

Revision ID: f42cd5deec4c
Revises: 
Create Date: 2025-12-17 18:30:11.601491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42cd5deec4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('within_diet', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal')
    # ### end Alembic commands ###
